### PR TITLE
Fix serde (de)serialization

### LINKED ISSUE #34: Serde stopped working in 0.7.1
Crash log with full backtrace
message.txt

### PR DESCRIPTION
**Pull request by funlennysub**
Fixes #34

### CODE REVIEW

File: tests/serde.rs [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+    );
+    hints.insert(
+        "PlayerAttributes.MapProperty.Key.StructProperty".to_string(),
+        "Struct".to_string(),
+    );
+
+    hints
+}
+
+#[test]
```
Comment (scottanderson) [inline tests/serde.rs:25]: Instead of making serde enabled by default, you could use `#[cfg(feature = "serde")]` to guard this test.

File: Cargo.toml [hunk 2]
```diff
@@ -21,3 +21,10 @@ thiserror = "1.0.40"
 
 [features]
 serde = ["dep:serde", "ordered-float/serde", "indexmap/serde"]
+
+[dev-dependencies]
+serde_json = "1.0.96"
+
+[[test]]
+name = "serde"
+required-features = ["serde"]
```
Comment (scottanderson) [inline Cargo.toml:30]: I would prefer not to make serde a default feature because the github workflow runner runs tests with serde enabled and with serde disabled, and this prevents it from running with serde disabled.

**Review by scottanderson — CHANGES_REQUESTED** [review]

File: tests/serde.rs [hunk 3]
```diff
@@ -0,0 +1,34 @@
...
...operty","value":"codex.Rumiko"},{"type":"StructProperty","value":{"CustomStruct":["Struct",[["AsFloat",{"type":"FloatProperty","value":1.0}],["AsString",{"type":"StrProperty","value":null}]]]}}]]},"PlayerAttributes":{"type":"MapProperty","key_type":"StructProperty","value_type":"FloatProperty","allocation_flags":0,"value":[[{"type":"StructProperty","value":{"CustomStruct":["Struct",[["AttributeName",{"type":"StrProperty","value":"Currency_Blueprints"}],["Attribute",{"type":"FieldPathProperty","value":{"path":["Currency_Blueprints"],"resolved_owner":"/Script/CD.CDPlayerAttributeSet"}}],["AttributeOwner",{"type":"ObjectProperty","value":"None"}]]]}},{"type":"FloatProperty","value":0.0}],[{"type":"StructProperty","value":{"CustomStruct":["Struct",[["AttributeName",{"type":"StrProperty","value":"Currency_Electrum"}],["Attribute",{"type":"FieldPathProperty","value":{"path":["Currency_Electrum"],"resolved_owner":"/Script/CD.CDPlayerAttributeSet"}}],["AttributeOwner",{"type":"ObjectProperty","value":"None"}]]]}},{"type":"FloatProperty","value":0.0}]]},"SecondaryWeaponClass":{"type":"ObjectProperty","value":"/Game/Weapons/RocketLauncher/Blueprints/BP_RocketLauncher.BP_RocketLauncher_C"}});
```
Comment (scottanderson) [inline tests/serde.rs:32]: This blob might be difficult to update in the future if the structure changes again. I would suggest removing this and the `assert_eq!`, but keep the `serde_json::to_value(&file.properties).unwrap()` statement. This will still serve the purpose of reproducing the enum issue.

Comment (scottanderson) [reply tests/serde.rs:32]: You can also pass `(&file)` rather than `(&file.properties)` to cover any potential issues related to values stored in the header.

File: Cargo.toml (hunk 2 above)
Comment (funlennysub) [reply Cargo.toml:30]: if you do `cargo test` it simply won't run the serde.rs test, but if you use `cargo test -F serde` it will.

Comment (scottanderson) [reply Cargo.toml:30]: Thanks for explaining, this should be fine.

File: Cargo.toml [hunk 4]
```diff
@@ -21,3 +21,10 @@ thiserror = "1.0.40"
 
 [features]
 serde = ["dep:serde", "ordered-float/serde", "indexmap/serde"]
+
+[dev-dependencies]
```
Comment (scottanderson) [inline Cargo.toml:25]: Can this be changed to `[target.'cfg(serde)'.dev-dependencies]`?

Comment (funlennysub) [reply Cargo.toml:25]: if you meant `'cfg(feature = "serde")'` according to [rust docs](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#platform-specific-dependencies) you'd have to use `[features]` section for that

File: tests/serde.rs (hunk 1 above)
Comment (scottanderson) [reply tests/serde.rs:25]: The related `use` caused the CI failure; you can fix that by moving the use into a block that is guarded by the suggestion above

**Review by scottanderson — APPROVED** [review]
